<!-- This code was generated by Builder.io -->
<script lang="ts">
	import { onMount } from 'svelte';
	import Logo from './Logo.svelte';

	let isMenuOpen = false;

	function toggleMenu() {
		isMenuOpen = !isMenuOpen;
	}

	onMount(() => {
		const handleKeyDown = (event: KeyboardEvent) => {
			if (event.key === 'Escape' && isMenuOpen) {
				isMenuOpen = false;
			}
		};

		window.addEventListener('keydown', handleKeyDown);

		return () => {
			window.removeEventListener('keydown', handleKeyDown);
		};
	});
</script>

<header class="flex flex-wrap gap-10 items-center pt-6 px-96 max-md:px-5">
	<nav>
		<ul class="flex flex-wrap gap-10 items-center list-none">
			<li>
				<a href="#unser-futter" class="text-xl font-medium leading-9 text-teal-950">
					Unser Futter
				</a>
			</li>
			<li>
				<a href="#so-funktionierts" class="text-xl font-medium leading-9 text-teal-950">
					So funktioniert's
				</a>
			</li>
			<li>
				<Logo />
			</li>
			<li>
				<a href="#uber-uns" class="text-xl font-medium leading-9 text-teal-950"> Über uns </a>
			</li>
			<li>
				<a href="#login" class="text-xl font-medium leading-9 text-teal-950"> Login </a>
			</li>
		</ul>
	</nav>
	<button
		class="md:hidden"
		on:click="{toggleMenu}"
		aria-expanded="{isMenuOpen}"
		aria-controls="mobile-menu"
	>
		Menu
	</button>
</header>

{#if isMenuOpen}
<div id="mobile-menu" class="md:hidden">
	<nav>
		<ul class="flex flex-col gap-4 p-4">
			<li>
				<a href="#unser-futter" class="text-xl font-medium leading-9 text-teal-950">
					Unser Futter
				</a>
			</li>
			<li>
				<a href="#so-funktionierts" class="text-xl font-medium leading-9 text-teal-950">
					So funktioniert's
				</a>
			</li>
			<li>
				<a href="#uber-uns" class="text-xl font-medium leading-9 text-teal-950"> Über uns </a>
			</li>
			<li>
				<a href="#login" class="text-xl font-medium leading-9 text-teal-950"> Login </a>
			</li>
		</ul>
	</nav>
</div>
{/if}
