<!-- This code was generated by Builder.io -->
<script lang="ts"></script>

<div
	class="flex overflow-hidden items-start self-stretch my-auto max-w-[151px] min-h-[100px] w-[151px]"
>
	<div class="flex overflow-hidden flex-col justify-center items-center min-h-[100px] w-[151px]">
		<img
			loading="lazy"
			src="https://cdn.builder.io/api/v1/image/assets/TEMP/3a76d02d645148e1ca2bab471b7f776515080e73184ec1388efde1dfe44e583c?placeholderIfAbsent=true&apiKey=b698d653ce7343c2a09f03a591179b5c"
			class="object-contain w-full aspect-[1.52]"
			alt="Company logo"
		/>
	</div>
</div>
